<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class CloneTablesUTITrans extends Command
{
    protected $signature = 'clone:CloneTablesUTITrans';

    protected $description = 'Clone filtered tables';

    public function handle()
    {
        $tables = [
            'purchase_orderdet' => 'id_detail',
            'sales_orderdet' => 'id',
            'mst_item_subsitute' => 'id',
            'invoice' => 'id',
            'sales_order' => 'id',
            'delivery_orderdet' => 'id',
            'unico_purchase_invoicedet' => 'id',
            'qo_history' => 'id',
            'ar_det' => 'id',
            'sales_orderdet_archive' => 'id',
            'outgoing_orderdet' => 'id',
            'quotation_detail' => 'id',
            'kps_pembelian_detail' => 'id',
            'archive_journal' => 'id',
            'inventory_detail' => 'id',
            'delivery_orderdet_archive' => 'id',
            'delivery_order' => 'id',
            'kps_po_detail' => 'id',
            'kps_pembelian' => 'id',
            'journal_transaction' => 'id',
            'purchase_billsdet' => 'id_detail',
            'kps_po' => 'id',
            'incoming_order_detail' => 'id_detail',
            'packing_list' => 'id',
            'mst_location' => 'id',
            'purchase_proses' => 'id',
            'outgoing_order' => 'id',
            'packing_number' => 'id',
            'purchase_order' => 'id',
            'purchase_request' => 'id',
            'unico_purchase_invoice' => 'id',
            'quotation_detail_dummy' => 'id',
            'kps_faktur_jual_detail' => 'id',
            'kps_sales_order_detail' => 'id',
            'delivery_order_archive' => 'id',
            'quotation' => 'id',
            'billingdet' => 'id',
            'inventory_Lastperiode' => 'id',
            'inventory_periode' => 'id',
            'kps_faktur_jual' => 'id',
            'sanco_journal_transactions' => 'id',
            'cbexpense_det' => 'id',
            'cbexpense' => 'id',
            'po_tmp' => 'id_detail',
            'inventory_np_periode_det' => 'id',
            'incoming_orderhistory' => 'id_detail',
            'shipping_list' => 'id',
            'outgoing_interchange' => 'id_outgoing',
            'data_stokopname' => 'id',
            'inventorykps_np_periode_det' => 'id',
            'inventory_np_periode' => 'id',
            'kps_sales_ordertmp' => 'id',
            'purchase_history' => 'id_detail',
            'oao_report' => 'id',
            'taxnum_det' => 'id',
            'purchaseinvoice_tmp' => 'id',
            'incoming_order' => 'id',
            'ap_invoice' => 'id_detail',
            'purchase_bills' => 'id',
            'price_contractdet' => 'id_detailpc',
            'sales_order_archive' => 'id',
            'inventory_periode_kps' => 'id',
            'inventoryKPS_lastperiode' => 'id',
            'sentra_invoice' => 'id',
            'kps_sales_order' => 'id',
            'sentra_delivery_orderdet_archive' => 'id',
            'sentra_sales_orderdet_archive' => 'id',
            'kps_purchase_billsdet' => 'id_detail',
            'sanco_sales_invoice_details' => 'id',
            'kps_ar_det_tenodji' => 'id',
            'ar' => 'id',
            'consigment_det' => 'id_detailpc',
            'sales_consigment_det' => 'id',
            'sentra_sales_order' => 'id',
            'sales_consigment' => 'id',
            'sanco_sales_invoices' => 'id',
            'sanco_purchase_invoice_details' => 'id',
            'ap_det' => 'id_detail',
            'kps_ar_det' => 'id',
            'sentra_purchase_orderdet' => 'id_detail',
            'sentra_delivery_orderdet' => 'id',
            'sentra_sales_orderdet' => 'id',
            'return_salesdet' => 'id_detail',
            'purchase_draftdet' => 'id',
            'oap_report' => 'id',
            'mst_customer' => 'id',
            'sanco_account_receivable_details' => 'id',
            'ap' => 'id',
            'ap_tmp' => 'id_detail',
            'billing' => 'id',
            'accmutation_det' => 'id',
            'mutation_outdet' => 'id',
            'inventory_detail_consigment' => 'id',
            'delivery_orderdet_consigment' => 'id',
            'inventory_balance_consigment' => 'id',
            'kps_archive_journal' => 'id',
            'kps_journal_transaction' => 'id',
            'sanco_oar' => 'id',
            'sanco_account_receivables' => 'id',
            'mutation_out' => 'id',
            'archive_oao' => 'id',
            'transfer_list' => 'id',
            'sentra_purchase_invoicedet' => 'id',
            'kps_numbering_purchase_invoice' => 'id',
            'kps_invoice_tenodji' => 'id',
            'jimshua_invoice' => 'id',
            'oslo_invoice' => 'id',
            'kps_invoice' => 'id',
            'aston_invoice' => 'id',
            'sentra_sales_order_archive' => 'id',
            'kps_oao_report_tenodji' => 'id',
            'kps_oao_report' => 'id',
            'kps_oao_report_hanguk' => 'id',
            'retursales_orderdet_history' => 'id',
            'return_sales' => 'id',
            'kps_cbexpense' => 'id',
            'purchase_draft' => 'id',
            'accmutation' => 'id',
            'kps_biaya_operasional' => 'id',
            'kps_ar_det_hanguk' => 'id',
            'slip_gaji_pajak_detail' => 'id',
            'kps_cbexpense_det' => 'id',
            'msg_journal_transaction' => 'id',
            'tmp_return_sales' => 'id',
            'kps_customer' => 'id',
            'kps_journal_transaction_tenodji' => 'id',
            'kps_purchase_billsdet_tenodji' => 'id_detail',
            'kps_ar_tenodji' => 'id',
            'oslo_ar_det' => 'id',
            'sanco_customers' => 'id',
            'item_production_detail' => 'id',
            'kps_pp_tmp' => 'id_detail',
            'slip_gaji' => 'id',
            'kps_accmutation_det' => 'id',
            'sentra_delivery_order' => 'id',
            'oslo_retur_jual' => 'id',
            'aston_faktur_jual' => 'id',
            'kps_purchase_billsdet_hanguk' => 'id_detail',
            'msg_faktur_jual' => 'id',
            'kps_numbering_sales_invoice' => 'id',
            'retursales_orderdet_doconsigment_history' => 'id',
            'kps_retur_jual' => 'id',
            'msg_ar_det' => 'id',
            'aston_retur_jual' => 'id',
            'jimshua_ar_det' => 'id',
            'sentra_delivery_order_archive' => 'id',
            'packing_list_recycle' => 'id',
            'oslo_faktur_jual' => 'id',
            'jimshua_retur_jual' => 'id',
            'aston_ar_det' => 'id',
            'jimshua_faktur_jual' => 'id',
            'sentra_mst_customer' => 'id',
            'inventory_unassembly_det' => 'id',
            'msg_cbexpense' => 'id',
            'kps_ap' => 'id',
            'kps_archive_oao' => 'id',
            'sentra_purchaseinvoice_tmp' => 'id',
            'msg_cbreceipt' => 'id',
            'kps_supplier' => 'id',
            'kps_pelunasan_piutang' => 'id',
            'inventory_detail_blacklist' => 'id',
            'kps_ap_tmp' => 'id_detail',
            'sanco_cb_expenses' => 'id',
            'mst_supplier' => 'id',
            'cbreceipt' => 'id',
            'kps_accmutation' => 'id',
            'kps_sales_quotation' => 'id',
            'kps_archive_journal_tenodji' => 'id',
            'unico_purchase_invoicedet_fixd' => 'id',
            'kps_ap_det' => 'id_detail',
            'oap_report_kps' => 'id',
            'jimshua_sales_order' => 'id',
            'aston_sales_order' => 'id',
            'kps_purchase_bills' => 'id',
            'oslo_sales_order' => 'id',
            'kps_pelunasan_hutang' => 'id',
            'oap_report_kps_tnj' => 'id',
            'msg_cbreceipt_det' => 'id',
            'mutation_indet' => 'id',
            'sanco_account_payables' => 'id',
            'kps_journal_transaction_hanguk' => 'id',
            'sanco_sales_invoice_numberings' => 'id',
            'kps_ar' => 'id',
            'tmp_stock_opname' => 'id',
            'performa_invoice_detail' => 'id',
            'kps_retur_order' => 'id',
            'oap_report_kps_hgk' => 'id',
            'sanco_purchase_invoices' => 'id',
            'sanco_account_receivable_lovs' => 'id',
            'sanco_cb_expense_details' => 'id',
            'sanco_sales_return_lovs' => 'id',
            'oap_report_KPS_TNJ' => 'id',
            'menu' => 'id',
            'kps_mutasi' => 'id',
            'kps_sales_quotation_detail' => 'id',
            'delivery_order_consigment' => 'id',
            'oap_report_KPS' => 'id',
            'msg_archive_journal' => 'id',
            'sentra_purchase_invoice' => 'id',
            'oap_report_KPS_HGK' => 'id',
            'emp_komisi' => 'id',
            'sanco_sales_return_details' => 'id',
            'item_assembly_det' => 'id',
            'inventory_unassembly' => 'id',
            'jimshua_purchase_billsdet' => 'id_detail',
            'unassembly' => 'id',
            'archive_oap' => 'id',
            'jimshua_sales_order_detail' => 'id',
            'kps_billingdet' => 'id',
            'inventoryjimshua_lastperiode' => 'id',
            'inventorykps_lastperiode_1' => 'id',
            'sanco_customer_deposits' => 'id',
            'oslo_supplier' => 'id',
            'return_orderdet' => 'id_detail',
            'inventoryaston_lastperiode' => 'id',
            'kps_inventory_balance' => 'id',
            'inventory_periode_oslo' => 'id',
            'kps_billingdet_tenodji' => 'id',
            'kps_retur_jual_detail' => 'id',
            'aston_sales_order_detail' => 'id',
            'sanco_cb_receipts' => 'id',
            'aston_pembelian' => 'id',
            'sentra_return_sales' => 'id',
            'sentra_purchase_order' => 'id',
            'oslo_purchase_billsdet' => 'id_detail',
            'aston_retur_jual_detail' => 'id',
            'sanco_debit_note_customers' => 'id',
            'oslo_sales_order_detail' => 'id',
            'sanco_billing_details' => 'id',
            'barang_tukardet' => 'id',
            'sanco_billing_detail_lovs' => 'id',
            'jimshua_pembelian' => 'id',
            'sanco_account_payable_details' => 'id',
            'oslo_faktur_jual_detail' => 'id',
            'sentra_qo_history' => 'id',
            'jimshua_retur_jual_detail' => 'id',
            'inventory_periode_jimshua' => 'id',
            'sentra_mst_supplier' => 'id',
            'kps_mst_coa' => 'id',
            'aston_supplier' => 'id',
            'kps_delivery_orderdet' => 'id',
            'return_order' => 'id',
            'jimshua_faktur_jual_detail' => 'id',
            'inventory_periode_aston' => 'id',
            'msg_cbexpense_det' => 'id',
            'kps_purchase_order' => 'id',
            'sanco_account_payable_lovs' => 'id',
            'aston_purchase_billsdet' => 'id_detail',
            'kps_archive_journal_hanguk' => 'id',
            'oslo_pembelian' => 'id',
            'cbreceipt_det' => 'id',
            'kps_approval' => 'id',
            'inventoryoslo_lastperiode' => 'id',
            'aston_faktur_jual_detail' => 'id',
            'oslo_retur_jual_detail' => 'id',
            'jimshua_supplier' => 'id',
            'changelogs_read' => 'id',
            'mst_karyawan' => 'id',
            'mst_coa' => 'id',
            'sanco_debit_notes' => 'id',
            'tmp_outgoingreport' => 'id',
            'jimshua_pembelian_detail' => 'id',
            'sanco_acc_mutation_numberings' => 'id',
            'oslo_customer' => 'id',
            'kps_mst_coa_tenodji' => 'id',
            'sentra_mst_warehouse' => 'id',
            'kps_accmutation_tenodji' => 'id',
            'sanco_users' => 'id',
            'sessions' => 'id',
            'pph_25' => 'id',
            'jimshua_customer' => 'id',
            'sanco_cb_expense_numberings' => 'id',
            'mst_cust_site' => 'id',
            'msg_accmutation' => 'id',
            'kps_mutasi_detail' => 'id',
            'archive_akun' => 'id',
            'kps_mst_coa_hanguk3' => 'id',
            'sanco_sales_returns' => 'id',
            'sanco_acc_mutation_details' => 'id',
            'kps_cbexpense_hanguk' => 'id',
            'sentra_mst_cust_site' => 'id',
            'purchase_tmp' => 'id',
            'aston_pembelian_detail' => 'id',
            'oslo_pembelian_detail' => 'id',
            'kps_ar_hanguk' => 'id',
            'packingdet' => 'id',
            'kps_pembelian_detail_temp' => 'id',
            'tbl_logoao' => 'id',
            'kps_mst_coa_tenodji3' => 'id',
            'warehousedet' => 'id',
            'kps_pelunasan_hutang_detail' => 'id',
            'kps_cbexpense_tenodji' => 'id',
            'kps_return_orderdet' => 'id_detail',
            'sanco_suppliers' => 'id',
            'kps_mst_coa_hanguk' => 'id',
            'kps_cbreceipt' => 'id',
            'kps_accmutation_hanguk' => 'id',
            'aston_pembelian_detail_temp' => 'id',
            'kps_pelunasan_piutang_detail' => 'id',
            'kps_cbreceipt_tenodji' => 'id',
            'jimshua_pembelian_detail_temp' => 'id',
            'sanco_cb_receipt_numberings' => 'id',
            'ar_balance' => 'id_balance',
            'sentra_quotation_detail' => 'id',
            'personal_access_tokens' => 'id',
            'referencesupplierrequest' => 'id',
            'kps_ref_pajak' => 'id',
            'mst_warehouse' => 'id',
            'sentra_return_salesdet' => 'id_detail',
            'kps_retur_orderdet' => 'id_detail',
            'pph_umkm' => 'id',
            'msg_mst_coa' => 'id',
            'kps_billingdet_hanguk' => 'id',
            'oslo_pembelian_detail_temp' => 'id',
            'sanco_cb_receipt_details' => 'id',
            'aston_customer' => 'id',
            'kps_cbreceipt_det_tenodji' => 'id',
            'aston_cbexpense_det' => 'id',
            'oslo_cbexpense' => 'id',
            'kps_jenis_biaya' => 'id',
            'msg_ar' => 'id',
            'sanco_sales_return_numberings' => 'id',
            'journal_manual' => 'id',
            'jobs' => 'id',
            'sc_history' => 'id',
            'jimshua_ar' => 'id',
            'user' => 'id',
            'roles' => 'id',
            'kps_numbering_debit_note' => 'id',
            'kps_purchase_bills_hanguk' => 'id',
            'jimshua_accmutation' => 'id',
            'cashreceipt' => 'id',
            'sanco_billing_numberings' => 'id',
            'jimshua_numbering_purchase_invoice' => 'id',
            'aston_accmutation_det' => 'id',
            'oslo_cbreceipt_det' => 'id',
            'kps_cbreceipt_det' => 'id',
            'aston_accmutation' => 'id',
            'sanco_salesname' => 'id',
            'jimshua_cbexpense' => 'id',
            'kps_numbering_kps_retur_order' => 'id',
            'role_has_permissions' => 'permission_id',
            'pph_25_detail' => 'id',
            'supplier_quotation_master' => 'id',
            'aston_ar' => 'id',
            'aston_cbexpense' => 'id',
            'permissions' => 'id',
            'unifikasi_detail' => 'id',
            'kps_delivery_order' => 'id',
            'sanco_account_payable_numberings' => 'id',
            'oslo_accmutation_det' => 'id',
            'kps_cbreceipt_hanguk' => 'id',
            'aston_numbering_purchase_invoice' => 'id',
            'model_has_roles' => 'role_id',
            'price_comparison_detail' => 'id',
            'oslo_ar' => 'id',
            'oslo_numbering_purchase_invoice' => 'id',
            'sanco_chart_of_accounts' => 'id',
            'umkm_matric' => 'id',
            'sanco_menus' => 'id',
            'ppn_detail' => 'id',
            'kps_perusahaan' => 'id',
            'users' => 'id',
            'pph_umkm_detail' => 'id',
            'jimshua_cbreceipt_det' => 'id',
            'barang_tukar' => 'id',
            'pr_tmp' => 'id',
            'kps_debit_note' => 'id',
            'oslo_cbexpense_det' => 'id',
            'kps_accmutation_det_tenodji' => 'id',
            'mst_tax' => 'id',
            'aston_cbreceipt_det' => 'id',
            'oslo_numbering_sales_invoice' => 'id',
            'oslo_cbreceipt' => 'id',
            'kps_cbexpense_det_hanguk' => 'id',
            'aston_cbreceipt' => 'id',
            'sanco_purchase_invoice_numberings' => 'id',
            'kps_ap_tenodji' => 'id',
            'kps_tax' => 'id',
            'failed_jobs' => 'id',
            'umkm_matric_detail' => 'id',
            'kps_purchase_bills_tenodji' => 'id',
            'aston_numbering_sales_invoice' => 'id',
            'jimshua_numbering_sales_invoice' => 'id',
            'jimshua_accmutation_det' => 'id',
            'kps_billing_tenodji' => 'id',
            'cashreceipt_det' => 'id',
            'kps_tax_tenodji' => 'id',
            'msg_accmutation_det' => 'id',
            'kps_billing' => 'id',
            'kps_cbexpense_det_tenodji' => 'id',
            'warehouse' => 'id',
            'oslo_accmutation' => 'id',
            'sanco_billings' => 'id',
            'kps_cbreceipt_det_hanguk' => 'id',
            'supplier_quotation' => 'id',
            'price_comparison_master' => 'id',
            'jimshua_cbexpense_det' => 'id',
            'sanco_acc_mutations' => 'id',
            'journal_manual_det' => 'id',
            'kps_accmutation_det_hanguk' => 'id',
            'purchase_request_master' => 'id',
            'jimshua_cbreceipt' => 'id',
            'oslo_journal_transaction' => 'id',
            'item_tmp_2' => 'id',
            'cash_disbursement' => 'id_cd',
            'companies' => 'id',
            'deposit_hgk' => 'id',
            'setting_akun' => 'id',
            'credit_notedet' => 'id_detail',
            'sentra_warehouse_contact_det' => 'id',
            'item_tmp' => 'id',
            'qofix_tmp' => 'id',
            'aston_archive_akun' => 'id',
            'oslo_archive_akun' => 'id',
            'aston_credit_note' => 'id',
            'oslo_ap' => 'id',
            'kps_quotation_detail' => 'id',
            'return_tmp' => 'id',
            'do_tmp_consigment' => 'id',
            'aston_billing' => 'id',
            'tbl_logoap' => 'id',
            'snk_archive_journal' => 'id',
            'sentra_quotation' => 'id',
            'oslo_ap_tmp' => 'id_detail',
            'unifikasi' => 'id',
            'price_comparison_history' => 'id',
            'quotation_sales_order' => 'id',
            'entertainment_nominees' => 'id',
            'qo_tmp' => 'id',
            'jimshua_debit_note' => 'id',
            'approval_settings' => 'id',
            'pricelist' => 'id',
            'oslo_pp_tmp' => 'id_detail',
            'deposit' => 'id',
            'insufficient_item' => 'id',
            'kps_ar_tmp_hanguk' => 'id',
            'mst_expedition' => 'id',
            'oap_report_aston' => 'id',
            'aston_mst_coa' => 'id',
            'deposit_kps' => 'id',
            'jimshua_taxnum' => 'id',
            'sentra_mst_department' => 'id',
            'kps_credit_note' => 'id',
            'kps_ap_det_hanguk' => 'id_detail',
            'mst_currency' => 'id',
            'assetdepreciation' => 'id',
            'msg_ap' => 'id',
            'aston_billingdet' => 'id',
            'oslo_oao_report' => 'id',
            'shippingcart_det' => 'id',
            'sentra_billingdet' => 'id',
            'mst_bank' => 'id',
            'reprint_request_form_details' => 'id',
            'price_contract' => 'id_pc',
            'salesorderconsigment_tmp' => 'id',
            'so_tmp' => 'id',
            'jimshua_ap' => 'id',
            'mst_coa_inject' => 'id',
            'sentra_fakturso' => 'id',
            'snk_archive_akun' => 'id',
            'billing_tmp' => 'id',
            'sentra_billing' => 'id',
            'kps_archive_akun_hanguk' => 'id',
            'menu_has_permissions' => 'id',
            'reprint_request_form' => 'id',
            'aston_taxnum' => 'id',
            'return_form' => 'id',
            'kps_fakturso' => 'id',
            'kps_ap_det_tenodji' => 'id_detail',
            'oap_report_oslo' => 'id',
            'mst_dimension' => 'id',
            'mst_taxes' => 'id',
            'aston_billing_tmp' => 'id',
            'oslo_billing' => 'id',
            'kps_group_access' => 'menu_id',
            'jimshua_mst_coa' => 'id',
            'oslo_billing_tmp' => 'id',
            'fakturso' => 'id',
            'price_comparison_tmp' => 'id',
            'kps_billing_hanguk_tmp' => 'id',
            'mst_group_coa' => 'id',
            'jimshua_ar_tmp' => 'id',
            'warehouse_contact_det' => 'id',
            'kps_billing_tmp' => 'id',
            'company_profile' => 'id',
            'kps_approval_det' => 'id',
            'item_assembly' => 'id',
            'mst_customer_warehouse' => 'id',
            'changelogs' => 'id',
            'balance_coa' => 'id',
            'jimshua_billing' => 'id',
            'jimshua_archive_akun' => 'id',
            'kps_taxnum_det_tenodji' => 'id',
            'kps_ref_ppn' => 'id',
            'mst_bucket' => 'id',
            'aston_billingdet_print' => 'id',
            'jimshua_billing_tmp' => 'id',
            'jimshua_ap_tmp' => 'id_detail',
            'msg_tbl_logyec' => 'id',
            'sentra_mst_bucket' => 'id',
            'oslo_debit_note' => 'id',
            'sjdo' => 'id',
            'sentra_sales_retursales_orderdet_history' => 'id',
            'sanco_roles' => 'id',
            'sentra_performa_invoice_detail' => 'id',
            'pl_create' => 'id',
            'aston_ap' => 'id',
            'salesorder_tmp' => 'id',
            'jimshua_purchase_bills' => 'id',
            'consigment' => 'id_pc',
            'sentra_tmp_return_sales' => 'id',
            'oslo_taxnum_det' => 'id',
            'kps_groups' => 'id',
            'kps_archive_akun' => 'id',
            'mutation_in' => 'id',
            'data_stokopname_tmp' => 'id',
            'kps_import_purchase' => 'id',
            'aston_purchase_bills' => 'id',
            'deposit_supplier' => 'id',
            'oslo_billingdet_print' => 'id',
            'job_batches' => 'id',
            'mst_site' => 'id',
            'promotion_nominees' => 'id',
            'return_invoicedet' => 'id',
            'oslo_ap_det' => 'id_detail',
            'importso_tmp' => 'id',
            'kps_billingdet_print_hanguk' => 'id',
            'aston_sales_ordertmp' => 'id',
            'mst_location_tmp' => 'id',
            'sanco_menu_parents' => 'id',
            'kps_config' => 'id',
            'sales_comparison' => 'id',
            'kps_archive_akun_tenodji' => 'id',
            'jimshua_billingdet_print' => 'id',
            'oap_report_jimshua' => 'id',
            'sentra_mst_customer_warehouse' => 'id',
            'kps_ar_tmp_tenodji' => 'id',
            'quotation_detail_sales_order' => 'id',
            'mst_contactdet' => 'id',
            'return_form_details' => 'id',
            'oslo_mst_coa' => 'id',
            'debit_note' => 'id',
            'warehouse_location' => 'id',
            'cash_disbursementdet' => 'id',
            'sentra_billing_tmp' => 'id',
            'salah_input' => 'pn',
            'aston_ap_det' => 'id_detail',
            'kps_menu' => 'menu_id',
            'jimshua_credit_note' => 'id',
            'sentra_do_tmp' => 'id',
            'debit_note_supplier' => 'id',
            'kps_billing_tenodji_tmp' => 'id',
            'kps_tbl_logyec' => 'id',
            'performa_invoice' => 'id',
            'kps_billingdet_print_tenodji' => 'id',
            'aston_mst_group_coa' => 'id',
            'kps_warehouse' => 'id',
            'item_production' => 'id',
            'oslo_ar_tmp' => 'id',
            'oslo_mst_group_coa' => 'id',
            'inventorykps_np_periode_det_1' => 'id',
            'rows_data' => 'id',
            'jimshua_sales_ordertmp' => 'id',
            'kps_sjdo' => 'id',
            'interchangepart_tmp' => 'id',
            'ppn' => 'id',
            'gl_approval' => 'id',
            'kps_ar_tmp' => 'id',
            'jimshua_journal_transaction' => 'id',
            'aston_oao_report' => 'id',
            'oslo_purchase_bills' => 'id',
            'sanco_oap' => 'id',
            'do_tmp' => 'id',
            'sales_comparison_detail' => 'id',
            'kps_billing_hanguk' => 'id',
            'mst_expense' => 'id',
            'archive_akun_inject' => 'id',
            'sanco_purchase_lov' => 'id',
            'validation_setting' => 'id',
            'jimshua_taxnum_det' => 'id',
            'sentra_mst_expedition' => 'id',
            'balanceKPS_coa' => 'id',
            'kps_ap_hanguk' => 'id',
            'kps_user' => 'user_id',
            'tmp_return' => 'id',
            'aston_pp_tmp' => 'id_detail',
            'msg_ap_det' => 'id_detail',
            'sentra_billingdet_print' => 'id',
            'mst_brand' => 'id',
            'slip_gaji_pajak' => 'id',
            'aston_debit_note' => 'id',
            'sanco_companies' => 'id',
            'st_document' => 'id',
            'jimshua_ap_det' => 'id_detail',
            'tmp_ganti_barang' => 'id',
            'kps_archive_oao_hanguk' => 'id',
            'aston_ap_tmp' => 'id_detail',
            'level' => 'id',
            'sentra_performa_invoice' => 'id',
            'aston_taxnum_det' => 'id',
            'jimshua_pp_tmp' => 'id_detail',
            'msg_mst_group_coa' => 'id',
            'credit_note' => 'id',
            'sentra_salesorder_tmp' => 'id',
            'oslo_taxnum' => 'id',
            'billingdet_print' => 'id',
            'kps_mst_group_coa' => 'id',
            'sanco_taxes' => 'id',
            'kps_taxnum_det' => 'id',
            'oslo_billingdet' => 'id',
            'ar_tmp' => 'id',
            'kps_kurs' => 'id',
            'mst_sales' => 'id',
            'kps_setting_akun' => 'id',
            'return_invoice' => 'id',
            'jimshua_oao_report' => 'id',
            'oslo_credit_note' => 'id',
            'migrations' => 'id',
            'stokunicolt1' => 'pn',
            'importpc_tmp' => 'id',
            'connections' => 'id',
            'mst_gudang' => 'id',
            'barang_kena_volume' => 'no',
            'aston_ar_tmp' => 'id',
            'deposit_supplier_tnj' => 'id',
            'aston_journal_transaction' => 'id',
            'kps_expedition' => 'id',
            'tbl_logyec' => 'id',
            'kps_billingdet_print' => 'id',
            'sentra_mst_sales' => 'id',
            'kps_approval_comments' => 'id',
            'kps_ap_tmp_hanguk' => 'id_detail',
            'mst_department' => 'id',
            'jimshua_billingdet' => 'id',
            'jimshua_mst_group_coa' => 'id',
            'oslo_sales_ordertmp' => 'id',
            'kps_ap_tmp_tenodji' => 'id_detail',
            'sanco_customer_deposit_numberings' => 'id',
            'data_stokopname_consignment' => 'id',
            'kps_taxnum' => 'id',
            'deposit_tnj' => 'id',
            'taxnum' => 'id',
            'msg_archive_akun' => 'id',
            'image_item' => 'id'
        ];


        foreach ($tables as $table => $primaryKey) {

            $this->newLine();
            $this->info("Processing table: {$table}");

            $total = DB::connection('source')
                ->table($table)
                ->count();

            $bar = $this->output->createProgressBar($total);

            $bar->start();

            DB::connection('source')
                ->table($table)
                ->orderBy($primaryKey)
                ->chunk(1000, function ($rows) use ($table, $primaryKey, $bar) {


                    // Cek cache
                    if (!isset($generatedColumnsCache[$table])) {
                        $generatedColumnsCache[$table] = DB::connection('target')
                            ->select("
                                SELECT COLUMN_NAME 
                                FROM INFORMATION_SCHEMA.COLUMNS 
                                WHERE TABLE_SCHEMA = DATABASE() 
                                AND TABLE_NAME = ? 
                                AND EXTRA LIKE '%GENERATED%'
                ", [$table]);
                    }

                    // Truncate table target sebelum insert (hanya sekali per tabel)
                    static $truncated = [];
                    if (!isset($truncated[$table])) {
                        DB::connection('target')->table($table)->truncate();
                        $truncated[$table] = true;
                        $this->info("Truncated table: {$table}");
                    }

                    $generatedNames = collect($generatedColumnsCache[$table])->pluck('COLUMN_NAME')->toArray();

                    $data = collect($rows)
                        ->map(fn ($row) => (array) $row)
                        ->map(function ($row) use ($generatedNames) {
                            return array_diff_key($row, array_flip($generatedNames));
                        })
                        ->toArray();

                    DB::connection('target')->statement('SET FOREIGN_KEY_CHECKS=0');
                    DB::connection('target')
                        ->table($table)
                        ->upsert($data, [$primaryKey]);

                    $bar->advance(count($data));
                });

            $bar->finish();
            $this->newLine();
            $this->info("Finished table: {$table}");

        }

        $this->info("Done All");
    }
}


// jalankan di bash
// php artisan clone:CloneTablesUTITrans
